# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class AppBuilderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BuildContainer = channel.unary_unary(
        '/AppBuilder/BuildContainer',
        request_serializer=service__pb2.BuildContainerRequest.SerializeToString,
        response_deserializer=service__pb2.BuildContainerResponse.FromString,
        )


class AppBuilderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def BuildContainer(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AppBuilderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BuildContainer': grpc.unary_unary_rpc_method_handler(
          servicer.BuildContainer,
          request_deserializer=service__pb2.BuildContainerRequest.FromString,
          response_serializer=service__pb2.BuildContainerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AppBuilder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
